
services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5433/rails_app
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=a7c982873e4d55be7d85b5bd7c784cd1db0b9604abf2ea0ad9b267f6be52ba63c24c281f66596d9b66990d962cbf65ef48c54cdb37aaec93b2c7f4261fb7eed5
      - DB_POOL=98
      - DB_PORT=5433
      - DB_HOST=db
      - RAILS_LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api2
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5433/rails_app
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=a7c982873e4d55be7d85b5bd7c784cd1db0b9604abf2ea0ad9b267f6be52ba63c24c281f66596d9b66990d962cbf65ef48c54cdb37aaec93b2c7f4261fb7eed5
      - DB_POOL=98
      - DB_PORT=5433
      - DB_HOST=db
      - RAILS_LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128MB'

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rails_app
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5433:5433"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1920MB'

volumes:
  postgres_data:
